sudo: required
services:
  - docker

before_install:
  - docker build -t kaurkaelep/multi-container -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true kaurkaelep/multi-container npm test -- --coverage

after_success:
  - docker build -t kaurkaelep/multi-client ./client
  - docker build -t kaurkaelep/multi-nginx ./nginx
  - docker build -t kaurkaelep/multi-server ./server
  - docker build -t kaurkaelep/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take these images and push them to docker hub
  - docker push kaurkaelep/multi-client
  - docker push kaurkaelep/multi-nginx
  - docker push kaurkaelep/multi-server
  - docker push kaurkaelep/multi-worker
